4.1
 1. Initialize an empty array with size 2X2.


In [ ]:
import numpy as np
arr = np.empty((2,2))
print("2 * 2 empty array:\n ", arr)

2 * 2 empty array:
  [[4.64631165e-310 0.00000000e+000]
 [4.64519106e-310 6.90882944e-310]]


 2. Initialize an all one array with size 4X2.


In [ ]:
import numpy as np
arr = np.ones((4,2));
print("All ones array:\n ",arr)


All ones array:
  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}


In [ ]:
import numpy as np
fill_value = 9
shape = (2,3)
filled_arr = np.full(shape,fill_value)
print("\nArray Filled with value 9(2*3): \n", filled_arr)



Array Filled with value 9(2*3): 
 [[9 9 9]
 [9 9 9]]


 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
*italicized text*

In [ ]:
import numpy as np
#example array
given_arr = np.array([[2,4],[5,6]])

#create a new array with zeroes with the same shape
zero_arr = np.zeros_like(given_arr)

print("Original array:\n", given_arr)
print("Array filled with zeroes:\n", zero_arr)


Original array:
 [[2 4]
 [5 6]]
Array filled with zeroes:
 [[0 0]
 [0 0]]


 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [ ]:
import numpy as np
example_arr = np.array([[1,2,3], [6,7,8]])
ones_arr = np.ones_like(example_arr)
print("Original array:\n", example_arr)
print("Array filled with ones:\n",ones_arr)

Original array:
 [[1 2 3]
 [6 7 8]]
Array filled with ones:
 [[1 1 1]
 [1 1 1]]


 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [ ]:
new_list = [1,2,3,4]
#converting to numpy array
numpy_arr = np.array(new_list)
print(numpy_arr)

[1 2 3 4]


 4.1.1 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arange()}.

In [ ]:
import numpy as np
arr_range = np.arange(10,50)
print("Array with values ranging from 10 to 49:\n", arr_range)

Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [ ]:
matrix = np.arange(0,9).reshape(3,3)
print("3X3 matrix with values ranging from 0 to 8:\n",matrix)


3X3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3,3)
print("Identity matrix: \n", identity_matrix)

Identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}


In [ ]:
random_arr =np.random.random(30)
mean = random_arr.mean()
print("Random array with size 30: \n", random_arr)
print("Mean of the array: \n", mean)

Random array with size 30: 
 [0.76408729 0.78366289 0.48317923 0.48547539 0.69535221 0.04306154
 0.83626135 0.46362576 0.98269887 0.13892722 0.28734969 0.35651401
 0.37990494 0.90274298 0.344788   0.00651078 0.79868649 0.01998036
 0.97958042 0.2757111  0.05425505 0.44031574 0.91311927 0.34540358
 0.19780699 0.21761626 0.85283835 0.23067314 0.88604415 0.78906422]
Mean of the array: 
 0.49850790841070186


 5. Create a 10X10 array with random values and find the minimum and maximum values.


In [ ]:
import numpy as np
random_array = np.random.random((10,10))
min_value = random_array.min()
max_value = random_array.max()
print("Array with 10 * 10 random values: \n", random_array)
print("Minimum value: ", min_value)
print("Maximum value: ", max_value)

Array with 10 * 10 random values: 
 [[0.9914313  0.37316961 0.31186518 0.9313915  0.98349703 0.5037142
  0.93892125 0.80368683 0.86147232 0.91652329]
 [0.94120216 0.59925953 0.4393781  0.19078342 0.02116066 0.95202459
  0.69366968 0.93797165 0.773698   0.2592831 ]
 [0.08613192 0.42206807 0.81403615 0.05703104 0.69649937 0.71541062
  0.5980059  0.25589871 0.44669795 0.67499904]
 [0.62060976 0.93187135 0.32174008 0.20444267 0.26384729 0.77558602
  0.89198845 0.91444424 0.11973321 0.41417192]
 [0.34670199 0.91193819 0.11453969 0.09058037 0.68979114 0.49543514
  0.29211641 0.71260374 0.40776868 0.0339795 ]
 [0.15578022 0.46176064 0.44846584 0.33167015 0.36848987 0.23231165
  0.8837614  0.08349025 0.15392182 0.52344175]
 [0.53354665 0.19191338 0.63968797 0.11196908 0.64748647 0.18537013
  0.7208604  0.39326919 0.67982712 0.06883859]
 [0.71564215 0.54809177 0.88151692 0.92112194 0.58072677 0.48286349
  0.33792634 0.26434512 0.14834789 0.73237298]
 [0.67819745 0.16292597 0.98689898 0.58270162

 6. Create a zero array of size 10 and replace 5th element with 1.


In [ ]:
import numpy as np
zero_arr = np.zeros(10)
# the 5th value represents 4th index
zero_arr[4] = 1
print("Zero array of size 10 and being element being replaced: \n", zero_arr)

Zero array of size 10 and being element being replaced: 
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


 7. Reverse an array arr = [1,2,0,0,4,0].


In [ ]:

arr = [1,2,0,0,4,0]
reverse_arr = arr[::-1]
print("Original array: ", arr)
print("The reversed array is: \n", reverse_arr)

Original array:  [1, 2, 0, 0, 4, 0]
The reversed array is: 
 [0, 4, 0, 0, 2, 1]


 8. Create a 2d array with 1 on border and 0 inside.


```
# This is formatted as code
```



In [ ]:
border_arr = np.ones((5,5))
border_arr[1:-1, 1:-1] = 0
print("2d array with 1 on border and 0 inside: \n", border_arr)

2d array with 1 on border and 0 inside: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


 9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [ ]:
checkerboard = np.zeros((8,8),dtype = int)
checkerboard[1::2, ::2] = 1  #fill alternate positions in odd rows
checkerboard[::2, 1::2] = 1 #fill alternate positions in even rows
print("8X8 matrix with a checkerboard pattern: \n", checkerboard)


8X8 matrix with a checkerboard pattern: 
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
#given arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#adding two arrays
addition = x + y
print("sum of x and y:\n", addition,"\n")

#subtracting two arrays
diff = x - y
print("Difference of x and y: \n", diff)

#multiplying the array v with integer 4
scalar_multiply = v * 4
print("Product of array: ", scalar_multiply)

#finding square of each element in the array x
s1 = x ** 2
s2 = y ** 2
s3 = v ** 2
s4  = w ** 2

print("\nsquare of each elements: \n")
print("x: ",s1)
print ("y: ",s2)
print("v: ",s3)
print("w: ",s4)

# finding the dot product
vw_dot = np.dot(v,w)
xv_dot = np.dot(x, v)
xy_dot = np.dot(x,y)
print("\n Dot product of v and w: ", vw_dot)
print("\n Dot product of x and v: ", xv_dot)
print("\n Dot product of x and y: ", xy_dot)

# concatenate x and y along rows, v and w along colums
concat_xy = np.concatenate((x,y), axis = 0) # along rows
concat_vw = np.vstack((v,w)) # along column
print("Concatenation of x and y along rows: \n", concat_xy)
print("Concatenation of v and w along column: \n", concat_vw)

#concatenate x and v
try:
  concat_xv = np.concatenate((x,v), axis = 0)
  print("\nConcatenation of x and v: \n", concat_xv)
except ValueError as e:
  print("\n Error while concatenatating x and v: ", e)

sum of x and y:
 [[ 6  8]
 [10 13]] 

Difference of x and y: 
 [[-4 -4]
 [-4 -3]]
Product of array:  [36 40]

square of each elements: 

x:  [[ 1  4]
 [ 9 25]]
y:  [[25 36]
 [49 64]]
v:  [ 81 100]
w:  [121 144]

 Dot product of v and w:  219

 Dot product of x and v:  [29 77]

 Dot product of x and y:  [[19 22]
 [50 58]]
Concatenation of x and y along rows: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along column: 
 [[ 9 10]
 [11 12]]

 Error while concatenatating x and v:  all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.

 2. Prove AB= BA.

 3. Prove (AB)T = BTAT.
 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1

 x −y+2z =−3

 3x +y−z =9
 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

In [ ]:
import numpy as np

#given matrices
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#1.
inverse_A = np.linalg.inv(A)  #calculates the inverse
identity_matrix = np.dot(A, inverse_A)  #A.A^-1
im_rounded = np.round(identity_matrix)

#Round to avoid floating point inaccuracies
print("A * A^-1 = Identity Matrix: \n", im_rounded)

#2.
AB = np.dot(A,B)
BA = np.dot(B, A)
is_commutative = np.array_equal(AB, BA)
print("AB: \n", AB)
print("BA: \n", BA)
print("Is equal to BA? ",is_commutative)

#3
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
is_transpose_property = np.array_equal(AB_T, BT_AT)
print("Transpose of AB: \n", AB_T)
print(" B^T * A^T: \n ", BT_AT)
print("Is (AB)^T equal to B^T * A ^ T ?", is_transpose_property)


#solving the system of linear equations
#Represent the eqn in matrix form: AX = B
coeff_matrix = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])

#coeff of x,y,x
rhs_matrix = np.array([-1,-3,9])  #right hand side constants

#solving using np.linalg.inv
A_inv_3x3 = np.linalg.inv(coeff_matrix) #inverse of coefficient matrix
solution = np.dot(A_inv_3x3, rhs_matrix)  #solve for X = A ^-1 * B
print("Solution to the system of eqn using inverse method: \n", solution)

#Solving using np.linalg.solve(more numerically stable)
sol_linalg = np.linalg.solve(coeff_matrix, rhs_matrix)
print("Solution to the system of eqn using np.linalg.solve: \n", sol_linalg)



A * A^-1 = Identity Matrix: 
 [[1. 0.]
 [0. 1.]]
AB: 
 [[23 13]
 [51 29]]
BA: 
 [[36 44]
 [13 16]]
Is equal to BA?  False
Transpose of AB: 
 [[23 51]
 [13 29]]
 B^T * A^T: 
  [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A ^ T ? True
Solution to the system of eqn using inverse method: 
 [ 2.  1. -2.]
Solution to the system of eqn using np.linalg.solve: 
 [ 2.  1. -2.]
